services:
  movie:
    build: ./movie
    ports:
      - "3200:3200"
    environment:
      - USE_MONGO=true
      - MONGO_URL=mongodb://mongo:27018/archiDistriDB
      - USE_DOCKER=true
    depends_on:
      - mongo
    restart: unless-stopped

  user:
    build: ./user/
    ports:
      - "3201:3203"
    environment:
      - USE_MONGO=true
      - MONGO_URL=mongodb://mongo:27018/archiDistriDB
      - USE_DOCKER=true
    depends_on:
      - mongo
    restart: unless-stopped

  booking:
    build: ./booking/
    ports:
      - "3202:5000"
    environment:
      - USE_MONGO=true
      - MONGO_URL=mongodb://mongo:27018/archiDistriDB
      - USE_DOCKER=true
    depends_on:
      - mongo
    restart: unless-stopped

  schedule:
    build: ./schedule/
    ports:
      - "3203:50051"
    environment:
      - USE_MONGO=true
      - MONGO_URL=mongodb://mongo:27018/archiDistriDB
      - USE_DOCKER=true
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
