openapi: 3.1.0
info:
  title: Users API
  version: 1.0.0
  description: API pour gérer les utilisateurs

servers:
  - url: http://127.0.0.1:3203
    description: Serveur local Users

paths:
  /users:
    get:
      summary: Récupérer tous les utilisateurs
      responses:
        '200':
          description: Succès
    post:
      summary: Créer un utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                last_active:
                  type: integer
            examples:
              user_example:
                summary: Exemple d'utilisateur
                value:
                  id: "celie_ponroy"
                  name: "Celie Ponroy"
                  last_active: 1360031050
      responses:
        '201':
          description: Utilisateur créé

  /users/{id}:
    get:
      summary: Récupérer un utilisateur par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Succès
    put:
      summary: Mettre à jour un utilisateur
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                last_active:
                  type: integer
                requester_id:
                  type: string
            examples:
              update_user_example:
                summary: Mise à jour utilisateur
                value:
                  name: "Celie Ponroy"
                  last_active: 1360031050
                  requester_id: "chris_rivers"
      responses:
        '200':
          description: Utilisateur mis à jour
    delete:
      summary: Supprimer un utilisateur
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                requester_id:
                  type: string
            examples:
              delete_user_example:
                summary: Supprimer un utilisateur
                value:
                  requester_id: "chris_rivers"
      responses:
        '200':
          description: Utilisateur supprimé
